version: '2'
services:
    msp-app:
        image: msp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://msp-mysql:3306/msp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=msp-elasticsearch:9300
        ports:
            - 8080:8080
    msp-mysql:
        extends:
            file: mysql.yml
            service: msp-mysql
    msp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: msp-elasticsearch
